"""empty message

Revision ID: 0e9a7f95e483
Revises: 8dfffff7980e
Create Date: 2018-11-29 19:19:39.472403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e9a7f95e483'
down_revision = '8dfffff7980e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rent', sa.Column('actype', sa.String(length=1), nullable=True))
    op.add_column('rent', sa.Column('advarr', sa.String(length=1), nullable=True))
    op.add_column('rent', sa.Column('deedtype', sa.String(length=15), nullable=True))
    op.add_column('rent', sa.Column('landlord', sa.Integer(), nullable=True))
    op.add_column('rent', sa.Column('mailto', sa.String(length=1), nullable=True))
    op.add_column('rent', sa.Column('price', sa.Numeric(precision=8, scale=2), nullable=True))
    op.add_column('rent', sa.Column('source', sa.String(length=15), nullable=True))
    op.add_column('rent', sa.Column('status', sa.String(length=1), nullable=True))
    op.add_column('rent', sa.Column('tenantname', sa.String(length=90), nullable=True))
    op.add_column('rent', sa.Column('tenure', sa.String(length=1), nullable=True))
    op.add_column('rent', sa.Column('titlegrade', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rent', 'titlegrade')
    op.drop_column('rent', 'tenure')
    op.drop_column('rent', 'tenantname')
    op.drop_column('rent', 'status')
    op.drop_column('rent', 'source')
    op.drop_column('rent', 'price')
    op.drop_column('rent', 'mailto')
    op.drop_column('rent', 'landlord')
    op.drop_column('rent', 'deedtype')
    op.drop_column('rent', 'advarr')
    op.drop_column('rent', 'actype')
    # ### end Alembic commands ###
