"""empty message

Revision ID: 16a99843589f
Revises: 48c088e24272
Create Date: 2018-11-30 18:46:31.968201

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '16a99843589f'
down_revision = '48c088e24272'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('property', 'rentcode')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('property', sa.Column('rentcode', mysql.VARCHAR(length=10), nullable=True))
    # ### end Alembic commands ###
