"""empty message

Revision ID: 1d0eaec28db4
Revises: 99c96616acc4
Create Date: 2018-12-13 22:52:32.644654

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1d0eaec28db4'
down_revision = '99c96616acc4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agent', 'rentcode')
    op.create_foreign_key(None, 'rent', 'agent', ['agent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rent', type_='foreignkey')
    op.add_column('agent', sa.Column('rentcode', mysql.VARCHAR(length=10), nullable=True))
    # ### end Alembic commands ###
