"""empty message

Revision ID: 2dfbb8feb8e4
Revises: 688583b6aea5
Create Date: 2018-12-20 23:00:36.964140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2dfbb8feb8e4'
down_revision = '688583b6aea5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('extrent', sa.Column('propaddr', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('extrent', 'propaddr')
    # ### end Alembic commands ###
