"""empty message

Revision ID: 450bc718389b
Revises: 50d194eb51ff
Create Date: 2019-02-17 21:22:11.125834

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '450bc718389b'
down_revision = '50d194eb51ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('extrent', sa.Column('tenantname', sa.String(length=30), nullable=True))
    op.drop_column('rent', 'frequency')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rent', sa.Column('frequency', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('extrent', 'tenantname')
    # ### end Alembic commands ###
