"""empty message

Revision ID: 48c088e24272
Revises: fdb5cfe7a98b
Create Date: 2018-11-30 18:45:56.287959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48c088e24272'
down_revision = 'fdb5cfe7a98b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'property', 'rent', ['rent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'property', type_='foreignkey')
    # ### end Alembic commands ###
