"""empty message

Revision ID: 4fdaccebeb58
Revises: 6ec87dba4a8c
Create Date: 2018-12-23 16:38:49.605731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fdaccebeb58'
down_revision = '6ec87dba4a8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('datef2',
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('date1', sa.Date(), nullable=True),
    sa.Column('date2', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('datef4',
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('date1', sa.Date(), nullable=True),
    sa.Column('date2', sa.Date(), nullable=True),
    sa.Column('date3', sa.Date(), nullable=True),
    sa.Column('date4', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('income',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paydate', sa.Date(), nullable=True),
    sa.Column('total', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('payer', sa.String(length=90), nullable=True),
    sa.Column('typebank_id', sa.Integer(), nullable=True),
    sa.Column('typepayment_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('incomealloc',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alloc_id', sa.Integer(), nullable=True),
    sa.Column('rentcode', sa.String(length=15), nullable=True),
    sa.Column('landlord', sa.Integer(), nullable=True),
    sa.Column('charge_id', sa.Integer(), nullable=True),
    sa.Column('total', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('income_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('typeactype',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('desc', sa.String(length=45), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('typeadvarr',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('desc', sa.String(length=45), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('typebankacc',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bankname', sa.String(length=45), nullable=True),
    sa.Column('accname', sa.String(length=60), nullable=True),
    sa.Column('sortcode', sa.Integer(), nullable=True),
    sa.Column('accnum', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('typedeed',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('desc', sa.String(length=45), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('typemailto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('desc', sa.String(length=45), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('typepayment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('desc', sa.String(length=45), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('typeproperty',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('desc', sa.String(length=45), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('typesalegrade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('desc', sa.String(length=45), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('typestatus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('desc', sa.String(length=45), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('typetenure',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('desc', sa.String(length=15), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('property', sa.Column('typeprop_id', sa.Integer(), nullable=True))
    op.add_column('rent', sa.Column('actype_id', sa.Integer(), nullable=True))
    op.add_column('rent', sa.Column('advarr_id', sa.Integer(), nullable=True))
    op.add_column('rent', sa.Column('deed_id', sa.Integer(), nullable=True))
    op.add_column('rent', sa.Column('mailto_id', sa.Integer(), nullable=True))
    op.add_column('rent', sa.Column('salegrade_id', sa.Integer(), nullable=True))
    op.add_column('rent', sa.Column('status_id', sa.Integer(), nullable=True))
    op.add_column('rent', sa.Column('tenure_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rent', 'tenure_id')
    op.drop_column('rent', 'status_id')
    op.drop_column('rent', 'salegrade_id')
    op.drop_column('rent', 'mailto_id')
    op.drop_column('rent', 'deed_id')
    op.drop_column('rent', 'advarr_id')
    op.drop_column('rent', 'actype_id')
    op.drop_column('property', 'typeprop_id')
    op.drop_table('typetenure')
    op.drop_table('typestatus')
    op.drop_table('typesalegrade')
    op.drop_table('typeproperty')
    op.drop_table('typepayment')
    op.drop_table('typemailto')
    op.drop_table('typedeed')
    op.drop_table('typebankacc')
    op.drop_table('typeadvarr')
    op.drop_table('typeactype')
    op.drop_table('incomealloc')
    op.drop_table('income')
    op.drop_table('datef4')
    op.drop_table('datef2')
    # ### end Alembic commands ###
