"""empty message

Revision ID: 50d194eb51ff
Revises: b5724a995475
Create Date: 2019-02-17 13:46:03.508190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50d194eb51ff'
down_revision = 'b5724a995475'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('typefreq',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('freqdet', sa.String(length=45), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('rent', sa.Column('freq_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'rent', 'typefreq', ['freq_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rent', type_='foreignkey')
    op.drop_column('rent', 'freq_id')
    op.drop_table('typefreq')
    # ### end Alembic commands ###
