"""empty message

Revision ID: 5608764544f8
Revises: 84481fcf2050
Create Date: 2018-12-16 22:28:01.309262

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5608764544f8'
down_revision = '84481fcf2050'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'charge', 'rent', ['rent_id'], ['id'])
    op.drop_column('charge', 'chargedesc')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('charge', sa.Column('chargedesc', mysql.VARCHAR(length=180), nullable=True))
    op.drop_constraint(None, 'charge', type_='foreignkey')
    # ### end Alembic commands ###
