"""empty message

Revision ID: 6721aff6d81c
Revises: 92b1592673fa
Create Date: 2019-02-18 23:46:09.986960

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6721aff6d81c'
down_revision = '92b1592673fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('property', 'proptype')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('property', sa.Column('proptype', mysql.VARCHAR(length=1), nullable=True))
    # ### end Alembic commands ###
