"""empty message

Revision ID: 674b627e616f
Revises: eb11628043b6
Create Date: 2018-11-29 00:18:25.228132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '674b627e616f'
down_revision = 'eb11628043b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rent', sa.Column('datecode', sa.String(length=15), nullable=True))
    op.add_column('rent', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'rent', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rent', type_='foreignkey')
    op.drop_column('rent', 'user_id')
    op.drop_column('rent', 'datecode')
    # ### end Alembic commands ###
