"""empty message

Revision ID: 688583b6aea5
Revises: 5608764544f8
Create Date: 2018-12-20 22:14:15.192128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '688583b6aea5'
down_revision = '5608764544f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('extmanager',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codename', sa.String(length=15), nullable=True),
    sa.Column('details', sa.String(length=180), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('extrent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rentcode', sa.String(length=10), nullable=True),
    sa.Column('rentpa', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('arrears', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('lastrentdate', sa.Date(), nullable=True),
    sa.Column('tenure', sa.String(length=1), nullable=True),
    sa.Column('owner', sa.String(length=10), nullable=True),
    sa.Column('source', sa.String(length=15), nullable=True),
    sa.Column('status', sa.String(length=1), nullable=True),
    sa.Column('extmanager_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['extmanager_id'], ['extmanager.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extrent_rentcode'), 'extrent', ['rentcode'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_extrent_rentcode'), table_name='extrent')
    op.drop_table('extrent')
    op.drop_table('extmanager')
    # ### end Alembic commands ###
