"""empty message

Revision ID: 6caa7060951d
Revises: f2d88e39d4e2
Create Date: 2019-05-15 22:56:16.899829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6caa7060951d'
down_revision = 'f2d88e39d4e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('loan_name', sa.String(length=30), nullable=True),
    sa.Column('loan_start_date', sa.Date(), nullable=True),
    sa.Column('loan_end_date', sa.Date(), nullable=True),
    sa.Column('loan_int_rate', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('loan_freq_id', sa.Integer(), nullable=True),
    sa.Column('loan_advarr_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['loan_advarr_id'], ['typeadvarr.id'], ),
    sa.ForeignKeyConstraint(['loan_freq_id'], ['typefreq.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('loan_trans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trans_date', sa.Date(), nullable=True),
    sa.Column('trans_amount', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('loan_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['loan_id'], ['loan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('loan_trans')
    op.drop_table('loan')
    # ### end Alembic commands ###
