"""empty message

Revision ID: 6ec87dba4a8c
Revises: 2dfbb8feb8e4
Create Date: 2018-12-20 23:27:47.267725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ec87dba4a8c'
down_revision = '2dfbb8feb8e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'extrent', 'extmanager', ['extmanager_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'extrent', type_='foreignkey')
    # ### end Alembic commands ###
