"""empty message

Revision ID: 73fb0d62eb59
Revises: 
Create Date: 2019-08-18 12:24:51.837762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73fb0d62eb59'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agdetails', sa.String(length=180), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chargetype',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chargedesc', sa.String(length=60), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('datef2',
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('date1', sa.Date(), nullable=True),
    sa.Column('date2', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('datef4',
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('date1', sa.Date(), nullable=True),
    sa.Column('date2', sa.Date(), nullable=True),
    sa.Column('date3', sa.Date(), nullable=True),
    sa.Column('date4', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('emailaccount',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('smtp_server', sa.String(length=60), nullable=True),
    sa.Column('smtp_port', sa.Integer(), nullable=True),
    sa.Column('smtp_timeout', sa.Integer(), nullable=True),
    sa.Column('smtp_debug', sa.Integer(), nullable=True),
    sa.Column('smtp_tls', sa.Integer(), nullable=True),
    sa.Column('smtp_user', sa.String(length=60), nullable=True),
    sa.Column('smtp_password', sa.String(length=60), nullable=True),
    sa.Column('smtp_sendfrom', sa.String(length=60), nullable=True),
    sa.Column('imap_server', sa.String(length=60), nullable=True),
    sa.Column('imap_port', sa.Integer(), nullable=True),
    sa.Column('imap_tls', sa.Integer(), nullable=True),
    sa.Column('imap_user', sa.String(length=60), nullable=True),
    sa.Column('imap_password', sa.String(length=60), nullable=True),
    sa.Column('imap_sentfolder', sa.String(length=60), nullable=True),
    sa.Column('imap_draftfolder', sa.String(length=60), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('extmanager',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codename', sa.String(length=15), nullable=True),
    sa.Column('details', sa.String(length=180), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('manager',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=90), nullable=True),
    sa.Column('addr1', sa.String(length=180), nullable=True),
    sa.Column('addr2', sa.String(length=180), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('typeactype',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actypedet', sa.String(length=45), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('typeadvarr',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('advarrdet', sa.String(length=45), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('typebankacc',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bankname', sa.String(length=45), nullable=True),
    sa.Column('accname', sa.String(length=60), nullable=True),
    sa.Column('sortcode', sa.String(length=10), nullable=True),
    sa.Column('accnum', sa.String(length=15), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('typedeed',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deedcode', sa.String(length=15), nullable=True),
    sa.Column('nfee', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('nfeeindeed', sa.String(length=45), nullable=True),
    sa.Column('interest', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('dcov', sa.Boolean(), nullable=True),
    sa.Column('licencetoassign', sa.Boolean(), nullable=True),
    sa.Column('insapprove', sa.Boolean(), nullable=True),
    sa.Column('insproduce', sa.Boolean(), nullable=True),
    sa.Column('alterations', sa.Boolean(), nullable=True),
    sa.Column('dwellingonly', sa.Boolean(), nullable=True),
    sa.Column('sublet', sa.Boolean(), nullable=True),
    sa.Column('info', sa.String(length=180), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('typefreq',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('freqdet', sa.String(length=45), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('typemailto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mailtodet', sa.String(length=45), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('typepayment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paytypedet', sa.String(length=45), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('typeproperty',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proptypedet', sa.String(length=45), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('typesalegrade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('salegradedet', sa.String(length=45), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('typestatus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('statusdet', sa.String(length=45), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('typetenure',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenuredet', sa.String(length=15), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('about_me', sa.String(length=140), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('extrent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rentcode', sa.String(length=20), nullable=True),
    sa.Column('tenantname', sa.String(length=30), nullable=True),
    sa.Column('propaddr', sa.String(length=180), nullable=True),
    sa.Column('agentdetails', sa.String(length=45), nullable=True),
    sa.Column('rentpa', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('arrears', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('lastrentdate', sa.Date(), nullable=True),
    sa.Column('tenure', sa.String(length=1), nullable=True),
    sa.Column('owner', sa.String(length=15), nullable=True),
    sa.Column('source', sa.String(length=15), nullable=True),
    sa.Column('status', sa.String(length=1), nullable=True),
    sa.Column('extmanager_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['extmanager_id'], ['extmanager.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extrent_rentcode'), 'extrent', ['rentcode'], unique=False)
    op.create_table('income',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paydate', sa.Date(), nullable=True),
    sa.Column('total', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('payer', sa.String(length=90), nullable=True),
    sa.Column('typebankacc_id', sa.Integer(), nullable=True),
    sa.Column('typepayment_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['typebankacc_id'], ['typebankacc.id'], ),
    sa.ForeignKeyConstraint(['typepayment_id'], ['typepayment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('landlord',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=90), nullable=True),
    sa.Column('addr', sa.String(length=180), nullable=True),
    sa.Column('details', sa.String(length=90), nullable=True),
    sa.Column('taxdate', sa.Date(), nullable=True),
    sa.Column('manager_id', sa.Integer(), nullable=True),
    sa.Column('bankacc_id', sa.Integer(), nullable=True),
    sa.Column('emailacc_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bankacc_id'], ['typebankacc.id'], ),
    sa.ForeignKeyConstraint(['emailacc_id'], ['emailaccount.id'], ),
    sa.ForeignKeyConstraint(['manager_id'], ['manager.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('loan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('loan_name', sa.String(length=30), nullable=True),
    sa.Column('loan_start_date', sa.Date(), nullable=True),
    sa.Column('loan_end_date', sa.Date(), nullable=True),
    sa.Column('loan_int_rate', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('loan_freq_id', sa.Integer(), nullable=True),
    sa.Column('loan_advarr_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['loan_advarr_id'], ['typeadvarr.id'], ),
    sa.ForeignKeyConstraint(['loan_freq_id'], ['typefreq.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('incomealloc',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alloc_id', sa.Integer(), nullable=True),
    sa.Column('rentcode', sa.String(length=15), nullable=True),
    sa.Column('landlord', sa.Integer(), nullable=True),
    sa.Column('total', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('chargetype_id', sa.Integer(), nullable=True),
    sa.Column('income_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['chargetype_id'], ['chargetype.id'], ),
    sa.ForeignKeyConstraint(['income_id'], ['income.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('loan_trans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trans_date', sa.Date(), nullable=True),
    sa.Column('trans_amount', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('loan_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['loan_id'], ['loan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rentcode', sa.String(length=15), nullable=True),
    sa.Column('tenantname', sa.String(length=90), nullable=True),
    sa.Column('rentpa', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('arrears', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('lastrentdate', sa.Date(), nullable=True),
    sa.Column('datecode', sa.String(length=10), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=True),
    sa.Column('price', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('email', sa.String(length=60), nullable=True),
    sa.Column('note', sa.String(length=120), nullable=True),
    sa.Column('landlord_id', sa.Integer(), nullable=True),
    sa.Column('agent_id', sa.Integer(), nullable=True),
    sa.Column('actype_id', sa.Integer(), nullable=True),
    sa.Column('advarr_id', sa.Integer(), nullable=True),
    sa.Column('deed_id', sa.Integer(), nullable=True),
    sa.Column('freq_id', sa.Integer(), nullable=True),
    sa.Column('mailto_id', sa.Integer(), nullable=True),
    sa.Column('salegrade_id', sa.Integer(), nullable=True),
    sa.Column('status_id', sa.Integer(), nullable=True),
    sa.Column('tenure_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['actype_id'], ['typeactype.id'], ),
    sa.ForeignKeyConstraint(['advarr_id'], ['typeadvarr.id'], ),
    sa.ForeignKeyConstraint(['agent_id'], ['agent.id'], ),
    sa.ForeignKeyConstraint(['deed_id'], ['typedeed.id'], ),
    sa.ForeignKeyConstraint(['freq_id'], ['typefreq.id'], ),
    sa.ForeignKeyConstraint(['landlord_id'], ['landlord.id'], ),
    sa.ForeignKeyConstraint(['mailto_id'], ['typemailto.id'], ),
    sa.ForeignKeyConstraint(['salegrade_id'], ['typesalegrade.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['typestatus.id'], ),
    sa.ForeignKeyConstraint(['tenure_id'], ['typetenure.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rent_rentcode'), 'rent', ['rentcode'], unique=True)
    op.create_table('charge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chargetype_id', sa.Integer(), nullable=True),
    sa.Column('chargestartdate', sa.Date(), nullable=True),
    sa.Column('chargetotal', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('chargedetails', sa.String(length=140), nullable=True),
    sa.Column('chargebalance', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('rent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['chargetype_id'], ['chargetype.id'], ),
    sa.ForeignKeyConstraint(['rent_id'], ['rent.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('property',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('propaddr', sa.String(length=180), nullable=True),
    sa.Column('rent_id', sa.Integer(), nullable=True),
    sa.Column('typeprop_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['rent_id'], ['rent.id'], ),
    sa.ForeignKeyConstraint(['typeprop_id'], ['typeproperty.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('property')
    op.drop_table('charge')
    op.drop_index(op.f('ix_rent_rentcode'), table_name='rent')
    op.drop_table('rent')
    op.drop_table('loan_trans')
    op.drop_table('incomealloc')
    op.drop_table('loan')
    op.drop_table('landlord')
    op.drop_table('income')
    op.drop_index(op.f('ix_extrent_rentcode'), table_name='extrent')
    op.drop_table('extrent')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('typetenure')
    op.drop_table('typestatus')
    op.drop_table('typesalegrade')
    op.drop_table('typeproperty')
    op.drop_table('typepayment')
    op.drop_table('typemailto')
    op.drop_table('typefreq')
    op.drop_table('typedeed')
    op.drop_table('typebankacc')
    op.drop_table('typeadvarr')
    op.drop_table('typeactype')
    op.drop_table('manager')
    op.drop_table('extmanager')
    op.drop_table('emailaccount')
    op.drop_table('datef4')
    op.drop_table('datef2')
    op.drop_table('chargetype')
    op.drop_table('agent')
    # ### end Alembic commands ###
