"""empty message

Revision ID: 7c3606a0a24c
Revises: cd08d8cd9abe
Create Date: 2018-12-13 21:19:13.987721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c3606a0a24c'
down_revision = 'cd08d8cd9abe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rent', sa.Column('email', sa.String(length=60), nullable=True))
    op.add_column('rent', sa.Column('note', sa.String(length=90), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rent', 'note')
    op.drop_column('rent', 'email')
    # ### end Alembic commands ###
