"""empty message

Revision ID: 84481fcf2050
Revises: 1d0eaec28db4
Create Date: 2018-12-16 22:10:53.844976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84481fcf2050'
down_revision = '1d0eaec28db4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chargetype',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chargedesc', sa.String(length=60), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('charge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chargetype', sa.Integer(), nullable=True),
    sa.Column('chargedesc', sa.String(length=180), nullable=True),
    sa.Column('startdate', sa.Date(), nullable=True),
    sa.Column('chargetotal', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('chargedetails', sa.String(length=140), nullable=True),
    sa.Column('chargebalance', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('rent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['chargetype'], ['chargetype.id'], ),
    sa.ForeignKeyConstraint(['rent_id'], ['rent.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('charge')
    op.drop_table('chargetype')
    # ### end Alembic commands ###
