"""empty message

Revision ID: 8dfffff7980e
Revises: 674b627e616f
Create Date: 2018-11-29 00:20:01.342903

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8dfffff7980e'
down_revision = '674b627e616f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('rent_ibfk_1', 'rent', type_='foreignkey')
    op.drop_column('rent', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rent', sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('rent_ibfk_1', 'rent', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
