"""empty message

Revision ID: 92b1592673fa
Revises: e13c5757104e
Create Date: 2019-02-18 21:36:16.329914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92b1592673fa'
down_revision = 'e13c5757104e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('charge', 'startdate')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('charge', sa.Column('startdate', sa.DATE(), nullable=True))
    # ### end Alembic commands ###
