"""empty message

Revision ID: 99c96616acc4
Revises: 7c3606a0a24c
Create Date: 2018-12-13 22:36:29.536353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99c96616acc4'
down_revision = '7c3606a0a24c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=90), nullable=True),
    sa.Column('addr', sa.String(length=180), nullable=True),
    sa.Column('rentcode', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('rent', sa.Column('agent_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rent', 'agent_id')
    op.drop_table('agent')
    # ### end Alembic commands ###
