"""empty message

Revision ID: a6bf51a4473d
Revises: 4fdaccebeb58
Create Date: 2018-12-23 16:58:14.386882

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a6bf51a4473d'
down_revision = '4fdaccebeb58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('incomealloc', 'chargetype_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('incomealloc', 'income_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('incomealloc', 'income_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('incomealloc', 'chargetype_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    # ### end Alembic commands ###
