"""empty message

Revision ID: b5724a995475
Revises: 60189f72811c
Create Date: 2018-12-23 20:04:17.061626

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b5724a995475'
down_revision = '60189f72811c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'rent', 'typeactype', ['actype_id'], ['id'])
    op.create_foreign_key(None, 'rent', 'typestatus', ['status_id'], ['id'])
    op.create_foreign_key(None, 'rent', 'typeadvarr', ['advarr_id'], ['id'])
    op.create_foreign_key(None, 'rent', 'typetenure', ['tenure_id'], ['id'])
    op.create_foreign_key(None, 'rent', 'typedeed', ['deed_id'], ['id'])
    op.create_foreign_key(None, 'rent', 'typemailto', ['mailto_id'], ['id'])
    op.create_foreign_key(None, 'rent', 'typesalegrade', ['salegrade_id'], ['id'])
    op.drop_column('rent', 'titlegrade')
    op.drop_column('rent', 'mailto')
    op.drop_column('rent', 'advarr')
    op.drop_column('rent', 'actype')
    op.drop_column('rent', 'tenure')
    op.drop_column('rent', 'status')
    op.drop_column('rent', 'deedtype')
    op.alter_column('typedeed', 'alterations',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.alter_column('typedeed', 'dcov',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.alter_column('typedeed', 'dwellingonly',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.alter_column('typedeed', 'insapprove',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.alter_column('typedeed', 'insproduce',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.alter_column('typedeed', 'licencetoassign',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.alter_column('typedeed', 'nfee',
               existing_type=mysql.DECIMAL(precision=8, scale=2),
               nullable=True)
    op.alter_column('typedeed', 'nfeeindeed',
               existing_type=mysql.VARCHAR(length=45),
               nullable=True)
    op.alter_column('typedeed', 'sublet',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.drop_column('typedeed', 'bankruptcy')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('typedeed', sa.Column('bankruptcy', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.alter_column('typedeed', 'sublet',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.alter_column('typedeed', 'nfeeindeed',
               existing_type=mysql.VARCHAR(length=45),
               nullable=False)
    op.alter_column('typedeed', 'nfee',
               existing_type=mysql.DECIMAL(precision=8, scale=2),
               nullable=False)
    op.alter_column('typedeed', 'licencetoassign',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.alter_column('typedeed', 'insproduce',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.alter_column('typedeed', 'insapprove',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.alter_column('typedeed', 'dwellingonly',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.alter_column('typedeed', 'dcov',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.alter_column('typedeed', 'alterations',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.add_column('rent', sa.Column('deedtype', mysql.VARCHAR(length=15), nullable=True))
    op.add_column('rent', sa.Column('status', mysql.VARCHAR(length=1), nullable=True))
    op.add_column('rent', sa.Column('tenure', mysql.VARCHAR(length=1), nullable=True))
    op.add_column('rent', sa.Column('actype', mysql.VARCHAR(length=1), nullable=True))
    op.add_column('rent', sa.Column('advarr', mysql.VARCHAR(length=1), nullable=True))
    op.add_column('rent', sa.Column('mailto', mysql.VARCHAR(length=1), nullable=True))
    op.add_column('rent', sa.Column('titlegrade', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'rent', type_='foreignkey')
    op.drop_constraint(None, 'rent', type_='foreignkey')
    op.drop_constraint(None, 'rent', type_='foreignkey')
    op.drop_constraint(None, 'rent', type_='foreignkey')
    op.drop_constraint(None, 'rent', type_='foreignkey')
    op.drop_constraint(None, 'rent', type_='foreignkey')
    op.drop_constraint(None, 'rent', type_='foreignkey')
    # ### end Alembic commands ###
