"""empty message

Revision ID: b603c12e82b2
Revises: d702b70268c2
Create Date: 2018-12-09 18:44:21.138119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b603c12e82b2'
down_revision = 'd702b70268c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'landlord', 'manager', ['manager'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'landlord', type_='foreignkey')
    # ### end Alembic commands ###
