"""empty message

Revision ID: cd08d8cd9abe
Revises: b603c12e82b2
Create Date: 2018-12-09 19:01:04.219158

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cd08d8cd9abe'
down_revision = 'b603c12e82b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('landlord', sa.Column('manager_id', sa.Integer(), nullable=True))
    op.drop_constraint('landlord_ibfk_1', 'landlord', type_='foreignkey')
    op.create_foreign_key(None, 'landlord', 'manager', ['manager_id'], ['id'])
    op.drop_column('landlord', 'manager')
    op.add_column('rent', sa.Column('landlord_id', sa.Integer(), nullable=True))
    op.drop_constraint('rent_ibfk_1', 'rent', type_='foreignkey')
    op.create_foreign_key(None, 'rent', 'landlord', ['landlord_id'], ['id'])
    op.drop_column('rent', 'landlord')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rent', sa.Column('landlord', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'rent', type_='foreignkey')
    op.create_foreign_key('rent_ibfk_1', 'rent', 'landlord', ['landlord'], ['id'])
    op.drop_column('rent', 'landlord_id')
    op.add_column('landlord', sa.Column('manager', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'landlord', type_='foreignkey')
    op.create_foreign_key('landlord_ibfk_1', 'landlord', 'manager', ['manager'], ['id'])
    op.drop_column('landlord', 'manager_id')
    # ### end Alembic commands ###
