"""empty message

Revision ID: d277e38015b5
Revises: 0e9a7f95e483
Create Date: 2018-11-29 19:27:37.988808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd277e38015b5'
down_revision = '0e9a7f95e483'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rentcode', sa.String(length=10), nullable=True),
    sa.Column('landlord', sa.Integer(), nullable=True),
    sa.Column('tenantname', sa.String(length=90), nullable=True),
    sa.Column('mailto', sa.String(length=1), nullable=True),
    sa.Column('rentpa', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('arrears', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('advarr', sa.String(length=1), nullable=True),
    sa.Column('lastrentdate', sa.Date(), nullable=True),
    sa.Column('frequency', sa.Integer(), nullable=True),
    sa.Column('datecode', sa.String(length=10), nullable=True),
    sa.Column('actype', sa.String(length=1), nullable=True),
    sa.Column('tenure', sa.String(length=1), nullable=True),
    sa.Column('source', sa.String(length=15), nullable=True),
    sa.Column('deedtype', sa.String(length=15), nullable=True),
    sa.Column('status', sa.String(length=1), nullable=True),
    sa.Column('titlegrade', sa.Integer(), nullable=True),
    sa.Column('price', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rent_rentcode'), 'rent', ['rentcode'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rent_rentcode'), table_name='rent')
    op.drop_table('rent')
    # ### end Alembic commands ###
