"""empty message

Revision ID: d702b70268c2
Revises: f54ac083eccf
Create Date: 2018-12-09 18:21:03.464641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd702b70268c2'
down_revision = 'f54ac083eccf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('manager',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=90), nullable=True),
    sa.Column('addr1', sa.String(length=180), nullable=True),
    sa.Column('addr2', sa.String(length=180), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key(None, 'rent', 'landlord', ['landlord'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rent', type_='foreignkey')
    op.drop_table('manager')
    # ### end Alembic commands ###
