"""empty message

Revision ID: e13c5757104e
Revises: 450bc718389b
Create Date: 2019-02-18 21:33:03.869269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e13c5757104e'
down_revision = '450bc718389b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('charge', sa.Column('chargestartdate', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('charge', 'chargestartdate')
    # ### end Alembic commands ###
