"""empty message

Revision ID: eb11628043b6
Revises: ad2a206d82d9
Create Date: 2018-11-28 23:57:25.179954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb11628043b6'
down_revision = 'ad2a206d82d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rentcode', sa.String(length=15), nullable=True),
    sa.Column('lastrentdate', sa.Date(), nullable=True),
    sa.Column('rentpa', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('arrears', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('frequency', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rent_rentcode'), 'rent', ['rentcode'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rent_rentcode'), table_name='rent')
    op.drop_table('rent')
    # ### end Alembic commands ###
