"""empty message

Revision ID: f2d88e39d4e2
Revises: 6721aff6d81c
Create Date: 2019-02-18 23:51:07.065069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2d88e39d4e2'
down_revision = '6721aff6d81c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'property', 'typeproperty', ['typeprop_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'property', type_='foreignkey')
    # ### end Alembic commands ###
