"""empty message

Revision ID: fdb5cfe7a98b
Revises: 8d4257c7a02a
Create Date: 2018-11-30 18:41:46.666477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdb5cfe7a98b'
down_revision = '8d4257c7a02a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('property_ibfk_1', 'property', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('property_ibfk_1', 'property', 'rent', ['rent_id'], ['id'])
    # ### end Alembic commands ###
