INSERT INTO mjinn.loan_trans 
SELECT 0, Date, -Amount, Memo,
CASE
	WHEN Memo LIKE "%COSL-SID%" THEN 1 
	WHEN Memo LIKE "%WTP-ROTH%" THEN 2
	WHEN Memo LIKE "%GAR-HSL%" THEN 3 
	WHEN Memo LIKE "%WTP-NEWP%" THEN 4 
	WHEN Memo LIKE "%WTP-KING%" THEN 5 
	WHEN Memo LIKE "%INV-SPS%" THEN 6 
	WHEN Memo LIKE "%DJ-MILE%" THEN 7 
	WHEN Memo LIKE "%SAHE-KH%" THEN 8	 
	WHEN Memo LIKE "%CB-YELD%" THEN 9 
	WHEN Memo LIKE "%BROWN-BASS%" THEN 10
	WHEN Memo LIKE "%KILVETON%" THEN 13
	WHEN Memo LIKE "%KAS-COAL%" THEN 14
	WHEN Memo LIKE "%BOT-P6%" THEN 15
	WHEN Memo LIKE "%CLIVE-PRE%" THEN 16
END
FROM yoda.bank_transaction
WHERE ID > 35257
AND Cat = 42
AND Memo LIKE "%nterest payment%"
ORDER BY Date
;